config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :release_year, :genre, :description, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-warning">
  <div class="container-fluid">
    <%= link_to 'Movie Manager', root_path, class: 'navbar-brand'  %>
    <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: 'nav-link active'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class: 'nav-link active'  %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Movie Manager</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <title>Hello, world!</title>
</head>
<body>

<%= render 'home/header' %>
<div class="container">
  <%= yield %>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

app/views/movies/_form.html.erb
 <%= form_with(model: movie) do |form| %>
    <% if movie.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

        <ul>
          <% movie.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :release_year, class: "form-label" %>
      <%= form.number_field :release_year, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :genre, class: "form-label" %>
      <%= form.text_field :genre, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :rating, class: "form-label" %>
      <%= form.text_field :rating, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<br/>
<%= link_to 'Show', @movie, class: "btn btn-secondary" %>
<%= link_to 'Back', movies_path, class: "btn btn-dark" %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table class="table">
  <thead class="table-dark">
    <tr class="text text-center">
      <th>Name</th>
      <th>Release year</th>
      <th>Genre</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr class="text text-center">
        <td><%= movie.name %></td>
        <td><%= movie.release_year %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.rating %></td>
        <td><%= link_to 'Show', movie%></td>
        <td><%= link_to 'Edit', edit_movie_path(movie)%></td>
        <td><%= button_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path, class: "btn btn-dark"%>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<br/>
<%= link_to 'Back', movies_path, class: "btn btn-dark" %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row align-items-start">
    <div class="col">
      <h1 class="text text-dark">
        <%= @movie.name %>
        <h4 class="text text-secondary"><%= @movie.release_year %></h4>
      </h1>
    </div>
    <div class="col">
      <h2 class="text-end">
          <span class="badge bg-warning border border-dark">
            <%= @movie.rating %>
          </span>
        </h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row align-items-start">
    <div class="col">
      <h3>
        <strong>Genre:</strong>
        <%= @movie.genre %>
      </h3>

      <p>
        <div class="border border-dark" style="padding: 10px">
          <%= @movie.description %>
        </div>
      </p>

      <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-warning" %>
      <%= link_to 'Back', movies_path, class: "btn btn-dark" %>
    </div>
  </div>
</div>